name: '@pqt/publish'
# description: 'A comprehensive GitHub Action that helps you (mostly) automate publishing a package – or monorepo of packages – to NPM and GitHub Packages. Correctly tagged and tries it's best to do it all without conflicts.'
author: 'Austin Paquette'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub authentication token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'white'